"""
Database Tool Executors

Contains the actual DB execution logic for each LangGraph tool.
Called directly by @tool functions in agent/tools.py — no dispatcher needed.

Cursor lifecycle
----------------
Every helper that opens a cursor wraps it in ``try/finally`` (FIX [H5])
so the cursor is always closed even when ``execute`` raises (syntax,
permission, timeout). A leaked cursor keeps the underlying connection in
an aborted-transaction state and gradually exhausts the pool.

Timeout enforcement
-------------------
User-facing queries run through ``operations.execute_sql_query``, which
sets a per-statement timeout (``SET MAX_EXECUTION_TIME`` / ``statement_timeout``)
before executing the query. The AI tool path used to skip this (FIX [H6]),
so a cross-join DoS generated by the LLM could hang the pool forever.
We now set ``adapter.get_set_timeout_sql(timeout_seconds=30)`` before the LLM-issued
query is executed.
"""

import logging
import re
from contextlib import contextmanager
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


# =============================================================================
# CONNECTION HELPER (Reusable for all tools)
# =============================================================================


@contextmanager
def get_tool_connection(db_config: dict):
    """
    Context manager for getting a database connection from db_config.

    Delegates to the singleton ConnectionManager so that the pool created at
    connect_db time is reused across all tool calls, avoiding the overhead of
    creating and tearing down a fresh pool on every invocation.

    Supports all database types via the adapter pattern:
    - PostgreSQL (psycopg2)
    - MySQL (mysql-connector)
    - SQL Server (pyodbc)
    - Oracle (oracledb)

    Usage:
        with get_tool_connection(db_config) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT 1")
    """
    from service.database.connection_manager import (
        get_connection_manager,
    )

    manager = get_connection_manager()
    with manager.get_connection_context(db_config) as conn:
        yield conn


# =============================================================================
# TOOL EXECUTOR
# =============================================================================


class AIToolExecutor:
    """Database tool implementations called directly by LangGraph @tool functions."""

    # =========================================================================
    # Tool Implementations
    # =========================================================================

    @staticmethod
    def _get_connection_status(user_id: str) -> Dict:
        """Get current connection status from context."""
        from service.database.context_sync import (
            get_default_context_sync,
        )

        context_sync = get_default_context_sync()

        connection = context_sync.get_connection(user_id)

        if connection.get("connected"):
            return {
                "connected": True,
                "db_type": connection.get("db_type"),
                "database": connection.get("database"),
                "host": connection.get("host"),
                "is_remote": connection.get("is_remote"),
                "schema": connection.get("schema"),
                "connected_at": connection.get("connected_at"),
            }
        else:
            return {"connected": False, "message": "Not connected to any database"}

    @staticmethod
    def _get_query_history(user_id: str) -> list[dict]:
        """Get recent SQL queries from database context memory."""
        from service.database.context_sync import (
            get_default_context_sync,
        )

        return get_default_context_sync().get_recent_queries(user_id)

    @staticmethod
    def _get_database_list(user_id: str, db_config: dict = None) -> Dict:
        """
        Get list of databases using db_config if available.

        Optimized to use passed db_config for direct database queries.
        """
        from service.database.context_sync import (
            get_default_context_sync,
        )

        context_sync = get_default_context_sync()

        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database server"}

        # If db_config is available, query databases directly
        if db_config:
            try:
                databases = AIToolExecutor._query_databases_with_config(db_config)
                return {
                    "databases": databases,
                    "current_database": connection.get("database"),
                    "count": len(databases),
                }
            except Exception as e:
                logger.warning(f"Failed to query databases: {e}")
                # Fall back to context-based response

        # Fallback: return current database from context
        current_db = connection.get("database")
        return {
            "databases": [current_db] if current_db else [],
            "current_database": current_db,
            "count": 1 if current_db else 0,
        }

    @staticmethod
    def _query_databases_with_config(db_config: dict) -> List[str]:
        """Query available databases using db_config (DBMS-agnostic)."""
        from service.database.adapters import get_adapter

        db_type = db_config.get("db_type", "postgresql")
        adapter = get_adapter(db_type)

        with get_tool_connection(db_config) as conn:
            cursor = None
            try:
                cursor = conn.cursor()

                # Use adapter for DBMS-agnostic database query
                query, params = adapter.get_databases_for_cache()
                cursor.execute(query, params) if params else cursor.execute(query)
                all_databases = [row[0] for row in cursor.fetchall()]

                # Filter out system databases using adapter
                system_dbs = adapter.get_system_databases()
                databases = [db for db in all_databases if db.lower() not in system_dbs]

                return databases
            finally:
                # FIX [H5]: close the cursor even when execute/fetch raises.
                if cursor is not None:
                    try:
                        cursor.close()
                    except Exception:
                        pass

    @staticmethod
    def _fetch_tables_with_config(db_config: dict, db_type: str, db_name: str = None) -> List[str]:
        """Fetch table names using db_config directly (DBMS-agnostic)."""
        from service.database.adapters import get_adapter

        tables = []
        adapter = get_adapter(db_type)

        with get_tool_connection(db_config) as conn:
            cursor = None
            try:
                cursor = conn.cursor()

                # Use explicit db_name if provided, else fall back to db_config
                effective_db_name = db_name or db_config.get("database", "")
                schema = db_config.get("schema", "public")
                query, params = adapter.get_all_tables_for_cache(effective_db_name, schema=schema)
                cursor.execute(query, params) if params else cursor.execute(query)

                tables = [row[0] for row in cursor.fetchall()]
            finally:
                # FIX [H5]: close the cursor even when execute/fetch raises.
                if cursor is not None:
                    try:
                        cursor.close()
                    except Exception:
                        pass

        logger.debug(f"Fetched {len(tables)} tables using db_config")
        return tables

    @staticmethod
    def _fetch_tables_and_columns(db_config: dict, db_type: str, db_name: str = None) -> tuple:
        """
        Fetch tables and columns with primary key info.

        Returns:
            tuple: (tables list, columns dict with {name, is_primary_key} objects)
        """
        # Fetch tables
        tables = AIToolExecutor._fetch_tables_with_config(db_config, db_type, db_name)

        # Fetch columns with primary key info
        columns = AIToolExecutor._batch_fetch_columns(db_config, tables, db_type, db_name)

        return tables, columns

    @staticmethod
    def _batch_fetch_columns(db_config: dict, tables: List[str], db_type: str, db_name: str = None) -> Dict[str, List]:
        """
        Batch fetch columns for all tables in a single query (DBMS-agnostic).

        Returns dict where values are lists of column objects with:
        - name: column name
        - is_primary_key: True if column is part of primary key

        Much faster than individual queries for each table.
        """
        from service.database.adapters import get_adapter

        columns = {}

        if not tables:
            return columns

        adapter = get_adapter(db_type)
        # Use explicit db_name if provided, else fall back to db_config
        effective_db_name = db_name or db_config.get("database", "")
        schema = db_config.get("schema", "public")

        with get_tool_connection(db_config) as conn:
            cursor = None
            try:
                cursor = conn.cursor()

                # Use adapter for DBMS-agnostic batch column query
                query, params = adapter.get_batch_columns_for_tables(effective_db_name, tables, schema=schema)

                if query is None:
                    return {}

                cursor.execute(query, params)

                for row in cursor.fetchall():
                    # Query now returns (table_name, column_name, column_key)
                    table_name = row[0]
                    column_name = row[1]
                    column_key = row[2] if len(row) > 2 else ""

                    if table_name not in columns:
                        columns[table_name] = []

                    # Build column object with primary key info
                    columns[table_name].append({"name": column_name, "is_primary_key": column_key == "PRI"})
            finally:
                # FIX [H5]: close the cursor even when execute/fetch raises.
                if cursor is not None:
                    try:
                        cursor.close()
                    except Exception:
                        pass

        # Ensure all tables have entries (even if empty)
        for table in tables:
            if table not in columns:
                columns[table] = []

        logger.debug(f"Batch fetched columns for {len(columns)} tables")
        return columns

    @staticmethod
    def _execute_query(user_id: str, query: str, max_rows: int = 100, db_config: dict = None) -> Dict:
        """Execute a SQL query using provided db_config."""
        from service.database.context_sync import (
            get_default_context_sync,
        )

        context_sync = get_default_context_sync()

        if not query:
            return {"error": "Query is required"}

        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        try:
            # Execute query with db_config (required in FastAPI)
            if db_config:
                logger.debug("Executing query with explicit db_config")
                result = AIToolExecutor._execute_query_with_db_config(db_config, connection, query, max_rows)
            else:
                return {"error": "No database config available. Please re-connect to the database."}

            # Log query to history
            database = connection.get("database")
            row_count = result.get("row_count", 0)
            status = "success" if result.get("status") == "success" else "error"
            context_sync.add_query(user_id, query, database, row_count, status)

            if result.get("status") == "success":
                # fetchmany(max_rows + 1) proves truncation but cannot prove an
                # exact database-wide total. Do not label the display count as
                # a total when additional rows may exist.
                total_rows = None if result.get("truncated") else result.get("row_count", 0)
                result_data = result.get("result", [])
                return {
                    "success": True,
                    "columns": result.get("columns", []),
                    "data": result_data,
                    "row_count": len(result_data),
                    "total_rows": total_rows,
                    "truncated": result.get("truncated", False),
                }
            else:
                return {"error": result.get("message", "Query execution failed")}

        except Exception as e:
            logger.error(f"Error executing query: {e}")

            # FIX [EC5]: mirror the missing-table cache-clear logic from
            # ``_execute_query_with_db_config`` here too, since this
            # outer scope has the actual ``user_id`` (the inner method
            # only has the connection dict, which does not carry
            # user_id). Different DBs phrase missing-table errors
            # differently — see the inner method for the full marker
            # list. Clearing the schema cache here ensures the next
            # AI turn refetches a fresh table list and stops
            # generating queries against the dropped table.
            try:
                err_msg_lower = str(e).lower()
                missing_table_markers = (
                    "relation" in err_msg_lower and "does not exist" in err_msg_lower,
                    "table or view does not exist" in err_msg_lower,
                    "invalid object name" in err_msg_lower,
                    "doesn't exist" in err_msg_lower and "table" in err_msg_lower,
                    "unknown table" in err_msg_lower,
                )
                if any(missing_table_markers) and user_id:
                    from service.context.context_service import ContextService

                    _db_for_clear = connection.get("database") if isinstance(connection, dict) else None
                    if _db_for_clear:
                        ContextService.clear_schema_context(user_id, _db_for_clear)
                        logger.info(
                            "Cleared schema cache for %s after missing-table error (outer): %s",
                            _db_for_clear,
                            str(e)[:200],
                        )
            except Exception as clear_err:
                logger.debug(
                    "Schema cache clear on missing-table error failed (outer, non-blocking): %s",
                    clear_err,
                )

            return {"error": str(e)}

    @staticmethod
    def _execute_query_with_db_config(db_config: Dict, connection: Dict, query: str, max_rows: int) -> Dict:
        """
        Execute a (read-only) query using an explicitly passed db_config.

        Timeout enforcement (FIX [H6]): the AI tool path used to skip the
        per-statement timeout that the user-facing ``execute_sql_query``
        sets. A cross-join DoS or slow analytical query generated by the
        LLM could hold a pool connection forever and eventually exhaust the
        pool for all users. We now set ``adapter.get_set_timeout_sql(30)``
        before executing the validated query.

        Cursor lifecycle (FIX [H5]): the cursor is created inside a
        ``try/finally`` so it is always closed even when execute/fetch
        raises.
        """
        import time

        from config import get_config
        from service.database.security import DatabaseSecurity

        Config = get_config()
        if not db_config:
            return {
                "status": "error",
                "message": "No database connection available. Please connect to a database first.",
            }

        db_type = db_config.get("db_type", "postgresql")

        # FIX [L10]: enforce the unified query-length limit on the AI path
        # too, so the agent cannot submit longer queries than the human
        # endpoint allows.
        if len(query) > Config.SQL_QUERY_MAX_LENGTH:
            return {
                "status": "error",
                "message": (f"Query too long. Maximum: {Config.SQL_QUERY_MAX_LENGTH} characters."),
            }

        # Security check
        analysis = DatabaseSecurity.analyze_sql_query(query)
        if not analysis["is_safe"]:
            return {
                "status": "error",
                "message": f"Query blocked for security reasons: {', '.join(analysis['warnings'])}",
            }

        if analysis["query_type"] not in ("SELECT", "WITH"):
            return {
                "status": "error",
                "message": f"READ-ONLY MODE: Only SELECT/WITH queries are allowed. {analysis['query_type']} is blocked.",
            }

        try:
            start_time = time.time()

            actual_max_rows = max_rows if max_rows else Config.MAX_QUERY_RESULTS

            from service.database.adapters import get_adapter

            adapter = get_adapter(db_type)

            with get_tool_connection(db_config) as conn:
                cursor = None
                try:
                    cursor = conn.cursor()

                    # FIX [EC6]: lightweight pre-query health check. A
                    # pooled connection that the DB server dropped
                    # (idle-timeout, restart, network blip) is only
                    # discovered when the user's query fails — and the
                    # broken connection is then *returned to the pool*
                    # and handed to the next query, producing cascading
                    # failures across every user sharing the pool. We
                    # issue a no-op SELECT first; if it raises, we
                    # surface a clear ConnectionError so the user
                    # reconnects, and mark the conn as ``_failed`` so
                    # ``ConnectionManager.return_connection`` discards
                    # it instead of pooling it. We deliberately do NOT
                    # auto-retry — retrying a non-idempotent read is
                    # risky.
                    try:
                        cursor.execute(adapter.get_health_check_sql())
                        cursor.fetchone()
                    except Exception as health_err:
                        logger.warning(
                            "AI-tool pre-query health check failed for %s: %s",
                            db_type,
                            health_err,
                        )
                        try:
                            setattr(conn, "_failed", True)
                        except Exception:
                            pass
                        raise ConnectionError("Connection lost, please reconnect") from health_err

                    # FIX [EC3]: Oracle has no SET TIMEOUT SQL statement —
                    # its timeout is enforced via the oracledb driver's
                    # per-connection ``call_timeout`` attribute. Detect
                    # the method via getattr and apply it directly to the
                    # connection before issuing the query. Other adapters
                    # (MySQL/PostgreSQL/SQL Server) use the SQL-string
                    # path below and do not define ``set_session_timeout``
                    # so this branch is a no-op for them.
                    set_session_timeout_fn = getattr(adapter, "set_session_timeout", None)
                    if callable(set_session_timeout_fn):
                        try:
                            set_session_timeout_fn(conn, 30)
                        except Exception as timeout_err:
                            logger.debug(
                                "Could not apply adapter.set_session_timeout: %s",
                                timeout_err,
                            )

                    # FIX [H6]: set a per-statement timeout BEFORE executing
                    # the LLM-issued query. Without this a cross-join DoS
                    # would hang a pool connection until the pool was
                    # exhausted. Mirrors operations.execute_sql_query.
                    timeout_sql = adapter.get_set_timeout_sql(timeout_seconds=30)
                    if timeout_sql:
                        try:
                            cursor.execute(timeout_sql)
                        except Exception as timeout_err:
                            # Best-effort: some adapters (e.g. Oracle, SQL
                            # Server) return None and skip this entirely; if
                            # the SET itself fails we still proceed because
                            # the user-facing path also tolerates this.
                            logger.debug(
                                "Could not set AI-tool statement timeout: %s",
                                timeout_err,
                            )

                    # Set schema for PostgreSQL if specified
                    if db_type == "postgresql":
                        schema = connection.get("schema", "public")
                        # Validate schema name to prevent SQL injection
                        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", schema):
                            raise ValueError(f"Invalid schema name: {schema}")
                        # FIX [M15]: use psycopg2.sql.Identifier to safely
                        # interpolate the schema name into SET search_path,
                        # rather than f-string interpolation. Even though the
                        # regex above rejects non-identifier characters, the
                        # Identifier-based approach is defense-in-depth and
                        # also handles edge cases (reserved words, mixed case).
                        try:
                            from psycopg2 import sql as _pg_sql

                            cursor.execute(_pg_sql.SQL("SET search_path TO {}").format(_pg_sql.Identifier(schema)))
                        except ImportError:
                            # psycopg2 not available — fall back to the
                            # regex-validated interpolation. The regex above
                            # ensures the schema is a safe identifier.
                            cursor.execute(f"SET search_path TO {schema}")

                    # Execute the query
                    cursor.execute(query)
                    rows = cursor.fetchmany(actual_max_rows + 1)

                    end_time = time.time()
                    execution_time = round((end_time - start_time) * 1000, 2)

                    # Get column names using adapter (DBMS-agnostic)
                    column_names = adapter.get_column_names_from_cursor(cursor)
                finally:
                    # FIX [H5]: close the cursor even when execute/fetch raises.
                    if cursor is not None:
                        try:
                            cursor.close()
                        except Exception:
                            pass

            # Process results outside connection context
            fetched_count = len(rows)
            truncated = fetched_count > actual_max_rows
            if truncated:
                rows = rows[:actual_max_rows]

            # Convert rows to list of dicts
            result_data = AIToolExecutor._serialize_rows(rows, column_names)
            row_count = len(result_data)

            logger.debug("AI tool executed query: %d rows in %.2fms", row_count, execution_time)

            return {
                "status": "success",
                "columns": column_names,
                "result": result_data,
                "row_count": row_count,
                "truncated": truncated,
                "execution_time_ms": execution_time,
            }

        except Exception as e:
            logger.error(f"Error in context-aware query execution: {e}")

            # FIX [EC5]: if the error indicates a missing/dropped table
            # (different DBs phrase this differently: PG says
            # "relation ... does not exist", SQL Server says "invalid
            # object name", Oracle says "table or view does not exist",
            # MySQL says "table ... doesn't exist"), invalidate the
            # schema cache for this database so the next call refetches
            # a fresh table list. Without this, the dropped table would
            # stay in the cache and the AI would keep generating queries
            # against it on every subsequent turn. We only clear when we
            # have the user_id+database context needed to target the
            # cache entry; failure to clear is non-blocking (the
            # query-error response is still returned).
            err_msg_lower = str(e).lower()
            missing_table_markers = (
                "relation" in err_msg_lower and "does not exist" in err_msg_lower,
                "table or view does not exist" in err_msg_lower,
                "invalid object name" in err_msg_lower,
                "doesn't exist" in err_msg_lower and "table" in err_msg_lower,
                "unknown table" in err_msg_lower,
            )
            if any(missing_table_markers):
                _user_id_for_clear = connection.get("user_id") if isinstance(connection, dict) else None
                _db_for_clear = connection.get("database") if isinstance(connection, dict) else None
                # The caller (_execute_query) has the user_id; we expose
                # the cache-clear request via a flag in the returned
                # dict so the caller can perform it with user_id in
                # hand. We also best-effort clear here using whatever
                # identity info we can recover from the connection dict.
                try:
                    if _user_id_for_clear and _db_for_clear:
                        from service.context.context_service import ContextService

                        ContextService.clear_schema_context(_user_id_for_clear, _db_for_clear)
                        logger.info(
                            "Cleared schema cache for %s after missing-table error: %s",
                            _db_for_clear,
                            str(e)[:200],
                        )
                except Exception as clear_err:
                    logger.debug(
                        "Schema cache clear on missing-table error failed (non-blocking): %s",
                        clear_err,
                    )

            return {"status": "error", "message": str(e)}

    @staticmethod
    def _serialize_rows(rows: List, column_names: List[str]) -> List[Dict]:
        """
        Convert database rows to JSON-serializable dictionaries.

        Handles special types: datetime, date, time, timedelta, Decimal,
        bytes/bytearray, UUID, Enum, IP addresses, and falls back to
        ``str(value)`` (with a debug log) for any other non-JSON-serializable
        type encountered.

        FIX [EC1]: previously only ``datetime`` (via ``isoformat``), ``bytes``,
        and ``Decimal`` were handled. PostgreSQL UUIDs came back as
        ``uuid.UUID`` objects, Enums/IPs/ranges came back as their native
        Python types, and ``json.dumps`` later raised ``TypeError``. That
        ``TypeError`` was caught at the LangGraph ``tool_executor`` layer
        and the LLM only saw a generic ``<tool_execution_error>`` even
        though the query had succeeded and its rows had been persisted to
        Firestore. We now serialize all common PostgreSQL/MySQL/Oracle
        custom types so the rows round-trip cleanly through ``json.dumps``.

        FIX [EC2]: previously all ``bytes`` values were decoded as UTF-8
        with ``errors="replace"``, silently corrupting binary BLOBs
        (images, PDFs, encrypted data) by replacing every non-UTF-8 byte
        with U+FFFD. We now first attempt a strict UTF-8 decode; if that
        fails OR the original bytes contain a NUL byte (a strong signal
        of binary content), we return a ``0x``-prefixed hex string
        (truncated to 256 hex chars / 128 bytes) so the LLM can at least
        see the value's shape and length without payload corruption.
        """
        # FIX [EC1]: import all custom-type modules up-front (cheap — these
        # are all stdlib and idempotent).
        import datetime as _dt
        import decimal as _decimal
        import enum as _enum
        import ipaddress as _ip
        import uuid as _uuid

        Decimal = _decimal.Decimal

        result_data = []
        for row in rows:
            row_dict = {}
            for i, col in enumerate(column_names):
                value = row[i]
                # Handle non-serializable types
                if value is None:
                    pass  # None is JSON serializable
                elif isinstance(value, bool):
                    # bool is a subclass of int; keep it as-is (JSON-native).
                    pass
                elif isinstance(value, (str, int, float)):
                    pass  # JSON-native
                elif isinstance(value, Decimal):
                    # FIX [EC1]: keep existing Decimal handling.
                    value = float(value)
                elif isinstance(value, _uuid.UUID):
                    # FIX [EC1]: PostgreSQL UUID columns come back as
                    # uuid.UUID objects — str() yields the canonical form.
                    value = str(value)
                elif isinstance(value, _enum.Enum):
                    # FIX [EC1]: Enum columns (e.g. Postgres enums) — use
                    # ``.value`` so the LLM sees the raw stored value, not
                    # ``MyEnum.NAME``.
                    value = value.value
                elif isinstance(value, (_ip.IPv4Address, _ip.IPv6Address)):
                    # FIX [EC1]: inet/cidr columns.
                    value = str(value)
                elif isinstance(value, _dt.timedelta):
                    # FIX [EC1]: PostgreSQL interval columns come back as
                    # datetime.timedelta; isoformat() does not exist on
                    # timedelta. Serialize as total seconds (float).
                    value = value.total_seconds()
                elif isinstance(value, _dt.time):
                    # FIX [EC1]: time columns — must come BEFORE the
                    # ``hasattr(value, "isoformat")`` branch below because
                    # datetime.datetime also has isoformat; ordering by
                    # specificity avoids mis-classification.
                    value = value.isoformat()
                elif isinstance(value, _dt.date):
                    # FIX [EC1]: date columns (datetime.date is the parent
                    # of datetime.datetime, so check date AFTER datetime).
                    value = value.isoformat()
                elif isinstance(value, _dt.datetime):
                    value = value.isoformat()
                elif isinstance(value, (bytes, bytearray)):
                    # FIX [EC2]: detect binary BLOBs vs. text. A NUL byte
                    # is a strong indicator of binary content; a strict
                    # UTF-8 decode failure is the other. Either way we
                    # hex-encode the bytes (truncated) instead of silently
                    # corrupting them with errors="replace".
                    raw = bytes(value)
                    is_binary = b"\x00" in raw
                    if not is_binary:
                        try:
                            value = raw.decode("utf-8")
                        except UnicodeDecodeError:
                            is_binary = True
                    if is_binary:
                        hex_str = raw.hex()
                        # Truncate to 256 hex chars (128 bytes) so a 50MB
                        # BLOB cannot blow up the LLM context window.
                        if len(hex_str) > 256:
                            hex_str = hex_str[:256] + f"...<truncated, {len(raw)} bytes total>"
                        logger.debug(
                            "Binary BLOB column %r hex-encoded (%d bytes)",
                            col,
                            len(raw),
                        )
                        value = f"0x{hex_str}"
                elif hasattr(value, "isoformat"):  # leftover datetime-likes
                    value = value.isoformat()
                else:
                    # FIX [EC1]: catch-all for any other non-JSON-serializable
                    # type (e.g. numpy scalars, custom ORM types, range
                    # types). ``str()`` is the safest universal fallback;
                    # we log at debug so a noisy type shows up in dev logs
                    # without spamming production.
                    logger.debug(
                        "Falling back to str() for non-serializable value of type %r in column %r",
                        type(value).__name__,
                        col,
                    )
                    value = str(value)
                row_dict[col] = value
            result_data.append(row_dict)

        return result_data

    @staticmethod
    def _get_table_indexes(user_id: str, table_name: str, db_config: dict = None) -> Dict:
        """Get indexes for a specific table."""
        from service.database.context_sync import (
            get_default_context_sync,
        )

        context_sync = get_default_context_sync()
        from service.database.adapters import get_adapter

        if not table_name:
            return {"error": "Table name is required"}

        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        db_type = connection.get("db_type", "postgresql")
        database = connection.get("database")
        schema = connection.get("schema", "public")

        try:
            adapter = get_adapter(db_type)
            query, params = adapter.get_indexes_query(table_name, db_name=database, schema=schema)

            if query is None:
                return {"error": f"Index query not supported for {db_type}"}

            indexes = []
            with get_tool_connection(db_config) as conn:
                cursor = None
                try:
                    cursor = conn.cursor()
                    cursor.execute(query, params)

                    for row in cursor.fetchall():
                        indexes.append(
                            {
                                "index_name": row[0],
                                "column_name": row[1] if len(row) > 1 else None,
                                "is_unique": bool(row[2]) if len(row) > 2 else False,
                                "is_primary": bool(row[3]) if len(row) > 3 else False,
                            }
                        )
                finally:
                    # FIX [H5]: close the cursor even when execute/fetch raises.
                    if cursor is not None:
                        try:
                            cursor.close()
                        except Exception:
                            pass

            return {"table": table_name, "indexes": indexes, "count": len(indexes)}
        except Exception as e:
            logger.exception(f"Error getting indexes for {table_name}")
            return {"error": str(e)}

    @staticmethod
    def _get_schema_overview(user_id: str, target_tables: Optional[List[str]] = None, db_config: dict = None) -> Dict:
        """
        Get an overview of the schema including columns and foreign keys for
        specific or all tables.

        Cache freshness (FIX [L11]): when ``target_tables`` is provided and
        one or more requested tables are NOT present in the cached schema
        context (e.g. a table created after the cache was populated), we
        explicitly fetch the missing tables' columns from the database,
        update the cache, and mark the missing tables in the response so the
        AI does not silently operate on incomplete schema. Previously these
        missing tables were dropped from the columns dict without any
        signal, so the AI would generate queries against stale schema.
        """
        from service.database.context_sync import (
            get_default_context_sync,
        )

        context_sync = get_default_context_sync()

        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        database = connection.get("database")
        db_type = connection.get("db_type", "postgresql")

        try:
            # 1. Try to get from stored context cache first (with TTL check)
            schema_context = context_sync.get_schema_context(user_id, database)
            if schema_context:
                cached_tables = schema_context.get("tables", [])
                cached_columns = dict(schema_context.get("columns", {}))

                # Determine tables to process
                tables = target_tables if target_tables else cached_tables

                # Safety checks
                if len(tables) > 50:
                    # FIX [EC7]: truncate the available_tables list so a
                    # database with 10,000+ tables does not produce a
                    # 50K+ token error response that overflows the LLM
                    # context window. We send the first 200 names plus a
                    # total count + truncated flag so the AI can decide
                    # to use the target_tables parameter for specificity.
                    _total = len(cached_tables)
                    _list = cached_tables[:200]
                    return {
                        "error": "Context Window Protection",
                        "message": (
                            f"You requested {len(tables)} tables, which "
                            "exceeds the safe limit of 50. Please narrow "
                            "down your target_tables list further. "
                            f"Showing first 200 of {_total} tables. Use "
                            "target_tables parameter to request specific "
                            "tables."
                        ),
                        "available_tables": _list,
                        "total_table_count": _total,
                        "truncated_table_list": _total > len(_list),
                    }

                # FIX [L11]: explicitly identify requested tables that are
                # NOT in the cache (e.g. recently-created tables). Fetch
                # their columns fresh and merge into the cached map so the
                # AI does not silently operate on incomplete schema.
                missing_tables = [t for t in tables if t not in cached_columns]
                refreshed_missing: List[str] = []
                if missing_tables and db_config is not None:
                    try:
                        fresh_columns = AIToolExecutor._batch_fetch_columns(
                            db_config, missing_tables, db_type, db_name=database
                        )
                        if fresh_columns:
                            cached_columns.update(fresh_columns)
                            refreshed_missing = [t for t in missing_tables if t in fresh_columns]
                            # Best-effort async schema refresh: persist the
                            # freshly-learned tables back into the context
                            # cache so subsequent calls hit. We update the
                            # cached table list as well so the new tables
                            # appear in future available_tables responses.
                            try:
                                updated_tables = list(dict.fromkeys(cached_tables + refreshed_missing))
                                context_sync.store_schema_context(
                                    user_id,
                                    database,
                                    updated_tables,
                                    cached_columns,
                                )
                            except Exception as refresh_err:
                                logger.warning("Async schema refresh failed: %s", refresh_err)
                    except Exception as fetch_err:
                        logger.warning(
                            "Could not refresh missing schema tables %s: %s",
                            missing_tables,
                            fetch_err,
                        )

                # Build the columns dict for the requested tables. Tables
                # that are still missing (could not be refreshed) get an
                # explicit empty entry plus a marker so the AI knows.
                columns: Dict[str, List] = {}
                unrefreshed_missing: List[str] = []
                for t in tables:
                    if t in cached_columns:
                        columns[t] = cached_columns[t]
                    else:
                        columns[t] = []
                        unrefreshed_missing.append(t)

                # Fetch foreign keys
                all_foreign_keys_result = AIToolExecutor._get_foreign_keys(user_id, db_config=db_config)
                fks = all_foreign_keys_result.get("foreign_keys", [])
                if target_tables:
                    target_set = set(target_tables)
                    fks = [
                        fk
                        for fk in fks
                        if fk.get("table_name") in target_set or fk.get("referenced_table") in target_set
                    ]

                response = {
                    "database": database,
                    "tables": tables,
                    "columns": columns,
                    "foreign_keys": fks,
                    "table_count": len(tables),
                    "foreign_key_count": len(fks),
                    "source": "context",
                }
                # FIX [L11]: surface missing-table info so the AI agent
                # can decide whether to retry / re-fetch schema.
                if refreshed_missing or unrefreshed_missing:
                    response["refreshed_missing_tables"] = refreshed_missing
                    response["unrefreshed_missing_tables"] = unrefreshed_missing
                    response["schema_partial"] = bool(unrefreshed_missing)
                return response

            # 2. If not cached or stale, fetch fresh (and store in context cache)
            all_tables = AIToolExecutor._fetch_tables_with_config(db_config, db_type, db_name=database)

            if not all_tables:
                return {
                    "database": database,
                    "tables": [],
                    "columns": {},
                    "foreign_keys": [],
                    "message": "No tables found",
                }

            # FIX [EC5]: detect tables that are still in the cached schema
            # context but were DROPPED from the DB. The cache key is
            # ``database`` only (see context_service.get_schema_context),
            # and FIX [L11] only handled the *new* table case. A dropped
            # table would otherwise linger in the cache, the AI would
            # generate queries against it, the DB would return "relation
            # does not exist", and the cache would NOT be invalidated —
            # repeating the failure on every subsequent call. We look at
            # the raw (TTL-bypassing) cache entry to compute the diff;
            # the subsequent ``store_schema_context`` call replaces the
            # cache so the dropped tables are physically removed.
            try:
                from service.context.context_service import ContextService

                raw_ctx = ContextService._get_context(user_id) or {}
                raw_schemas = raw_ctx.get("database_schemas", {}) or {}
                raw_entry = raw_schemas.get(database) or {}
                cached_table_list = list(raw_entry.get("tables", []) or [])
                if cached_table_list:
                    fresh_set = set(all_tables)
                    stale_tables = [t for t in cached_table_list if t not in fresh_set]
                    if stale_tables:
                        logger.info(
                            "Removed %d stale table(s) from schema cache: %s",
                            len(stale_tables),
                            stale_tables[:50],
                        )
                        # The cache is replaced wholesale below by
                        # ``store_schema_context(user_id, database,
                        # all_tables, columns)`` — no explicit per-table
                        # delete needed. We log so operators can see the
                        # churn.
            except Exception as stale_err:
                logger.debug(
                    "Stale-table detection failed (non-blocking): %s",
                    stale_err,
                )

            # Determine tables to process
            if target_tables:
                tables = target_tables
                if len(tables) > 50:
                    # FIX [EC7]: truncate available_tables (see above for
                    # full rationale). Same 200-name cap + total count +
                    # truncated flag, so an LLM hitting this branch on a
                    # 10k-table database still gets a usable response.
                    _total = len(all_tables)
                    _list = all_tables[:200]
                    return {
                        "error": "Context Window Protection",
                        "message": (
                            f"You requested {len(tables)} tables, which "
                            "exceeds the safe limit of 50. Please narrow "
                            "down your target_tables list further. "
                            f"Showing first 200 of {_total} tables. Use "
                            "target_tables parameter to request specific "
                            "tables."
                        ),
                        "available_tables": _list,
                        "total_table_count": _total,
                        "truncated_table_list": _total > len(_list),
                    }
            else:
                if len(all_tables) > 50:
                    # FIX [EC7]: same truncation pattern as above.
                    _total = len(all_tables)
                    _list = all_tables[:200]
                    return {
                        "error": "Context Window Protection",
                        "message": (
                            f"This database contains {_total} tables. "
                            "Visualizing or fetching the entire schema at "
                            "once will exceed context limits. Please "
                            "specify a focused list of 'target_tables' to "
                            f"explore. Showing first 200 of {_total} tables."
                        ),
                        "available_tables": _list,
                        "total_table_count": _total,
                        "truncated_table_list": _total > len(_list),
                    }
                tables = all_tables

            # Get Columns
            columns = AIToolExecutor._batch_fetch_columns(db_config, tables, db_type, db_name=database)

            # Store fresh tables and columns in context cache (this will also record a store operation)
            context_sync.store_schema_context(user_id, database, all_tables, columns)

            # Get Foreign Keys
            all_foreign_keys_result = AIToolExecutor._get_foreign_keys(user_id, db_config=db_config)
            fks = all_foreign_keys_result.get("foreign_keys", [])
            if target_tables:
                target_set = set(target_tables)
                fks = [
                    fk for fk in fks if fk.get("table_name") in target_set or fk.get("referenced_table") in target_set
                ]

            return {
                "database": database,
                "tables": tables,
                "columns": columns,
                "foreign_keys": fks,
                "table_count": len(tables),
                "foreign_key_count": len(fks),
                "source": "fresh",
            }
        except Exception as e:
            logger.exception("Error getting schema overview")
            return {"error": str(e)}

    @staticmethod
    def _get_foreign_keys(user_id: str, table_name: str = None, db_config: dict = None) -> Dict:
        """Get foreign key relationships."""
        from service.database.context_sync import (
            get_default_context_sync,
        )

        context_sync = get_default_context_sync()
        from service.database.adapters import get_adapter

        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        db_type = connection.get("db_type", "postgresql")
        database = connection.get("database")
        schema = connection.get("schema", "public")

        try:
            adapter = get_adapter(db_type)
            query, params = adapter.get_foreign_keys_query(table_name, db_name=database, schema=schema)

            if query is None:
                return {"error": f"Foreign keys query not supported for {db_type}"}

            foreign_keys = []
            with get_tool_connection(db_config) as conn:
                cursor = None
                try:
                    cursor = conn.cursor()
                    cursor.execute(query, params)

                    for row in cursor.fetchall():
                        foreign_keys.append(
                            {
                                "table_name": row[0],
                                "column_name": row[1] if len(row) > 1 else None,
                                "referenced_table": row[2] if len(row) > 2 else None,
                                "referenced_column": row[3] if len(row) > 3 else None,
                            }
                        )
                finally:
                    # FIX [H5]: close the cursor even when execute/fetch raises.
                    if cursor is not None:
                        try:
                            cursor.close()
                        except Exception:
                            pass

            result = {"foreign_keys": foreign_keys, "count": len(foreign_keys)}
            if table_name:
                result["table"] = table_name

            return result
        except Exception as e:
            logger.exception("Error getting foreign keys")
            return {"error": str(e)}

    # =========================================================================
    # New AI tools: explain_query, get_table_details, get_table_row_count,
    # list_views. (get_foreign_keys already exists above and is reused as
    # the backing implementation for the new standalone get_foreign_keys
    # @tool function — it already supports the optional ``table_name``
    # filter.)
    # =========================================================================

    @staticmethod
    def _explain_query(
        user_id: str,
        db_config: dict,
        query: str,
        max_rows: int = 50,
    ) -> Dict:
        """Get the query execution plan for a read-only SQL statement.

        Purpose
        -------
        Lets the AI inspect the optimizer's plan for a SELECT/WITH query so
        it can diagnose slow queries, missing indexes, full-table scans, and
        bad join orderings. The system prompt advertises "performance"
        support — this tool is what backs that claim.

        Safety
        ------
        ``query`` is validated as read-only (SELECT/WITH only) via
        ``DatabaseSecurity.analyze_sql_query`` before being handed to the
        adapter. We deliberately do NOT use ``EXPLAIN ANALYZE`` on
        PostgreSQL/MySQL because ANALYZE actually executes the query — for
        arbitrary LLM-generated SQL on a shared pool, that's an
        unacceptable side-effect (locks, triggers via views, resource cost).

        Adapter dispatch
        ----------------
        Each adapter exposes:
          * ``explain_format`` — a tag the AI uses to interpret the rows
            ("json" for MySQL/PostgreSQL, "text" for SQL Server/Oracle).
          * ``run_explain(cursor, query)`` — handles DBMS-specific
            multi-statement orchestration (SQL Server SET SHOWPLAN_TEXT
            ON/OFF, Oracle EXPLAIN PLAN + DBMS_XPLAN.DISPLAY).

        Returns
        -------
        ``{"success": True, "plan": rows, "plan_format": <str>,
        "query": <str>}`` on success, or ``{"error": ...}`` on failure.
        """
        from service.database.adapters import get_adapter
        from service.database.context_sync import get_default_context_sync
        from service.database.security import DatabaseSecurity

        if not query:
            return {"error": "Query is required"}

        context_sync = get_default_context_sync()
        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        # Reuse the same read-only gate as execute_query so a malicious or
        # confused LLM cannot EXPLAIN an UPDATE/DELETE and observe which
        # rows would be touched.
        try:
            analysis = DatabaseSecurity.analyze_sql_query(query)
        except Exception as exc:
            return {"error": f"Query could not be safely parsed: {exc}"}
        if not analysis["is_safe"]:
            reason = "; ".join(analysis["warnings"]) or "query is not read-only"
            return {"error": f"Query blocked for security reasons: {reason}"}
        if analysis["query_type"] not in ("SELECT", "WITH"):
            return {
                "error": (
                    f"READ-ONLY MODE: Only SELECT/WITH queries are allowed "
                    f"for EXPLAIN. {analysis['query_type']} is blocked."
                )
            }

        db_type = connection.get("db_type", "postgresql")

        try:
            adapter = get_adapter(db_type)
            with get_tool_connection(db_config) as conn:
                cursor = None
                try:
                    cursor = conn.cursor()
                    raw_rows = adapter.run_explain(cursor, query)
                finally:
                    # FIX [H5]: close the cursor even when execute/fetch raises.
                    if cursor is not None:
                        try:
                            cursor.close()
                        except Exception:
                            pass

            # Bound the plan rows so a pathological plan (e.g. a 1000-way
            # join) cannot overflow the LLM context window.
            truncated = False
            if max_rows and isinstance(raw_rows, list) and len(raw_rows) > max_rows:
                raw_rows = raw_rows[:max_rows]
                truncated = True

            # Serialize the plan rows through the same JSON-safe pipeline
            # used by execute_query so DB-native types (datetime, Decimal,
            # UUID, bytes, ...) round-trip cleanly.
            # For JSON-format plans (MySQL/PG), the first column of the
            # single row is the JSON document; preserve it as a string so
            # the AI sees the raw JSON. For text-format plans (SQL Server/
            # Oracle), each row is a line of plan text.
            synthetic_col_names = [f"col_{i}" for i in range(len(raw_rows[0]) if raw_rows else 0)]
            plan_rows = AIToolExecutor._serialize_rows(
                raw_rows,
                synthetic_col_names,
            )

            # Best-effort: if the plan is a single-row single-column JSON
            # document (MySQL / PostgreSQL FORMAT JSON), unwrap it so the
            # AI sees the parsed JSON object instead of a JSON-encoded
            # string wrapped in another JSON string.
            if adapter.explain_format == "json" and len(plan_rows) == 1 and len(plan_rows[0]) >= 1:
                first_val = plan_rows[0][next(iter(plan_rows[0]))]
                if isinstance(first_val, str):
                    try:
                        import json as _json

                        unwrapped = _json.loads(first_val)
                        plan_rows = [unwrapped]
                    except Exception:
                        # Leave as-is; the AI can still read the raw string.
                        pass

            result = {
                "success": True,
                "plan": plan_rows,
                "plan_format": adapter.explain_format,
                "query": query,
                "row_count": len(plan_rows),
            }
            if truncated:
                result["truncated"] = True
            return result
        except Exception as e:
            logger.exception("Error getting EXPLAIN plan for query")
            return {"error": str(e)}

    @staticmethod
    def _get_table_details(user_id: str, db_config: dict, table_name: str) -> Dict:
        """Get detailed per-column schema for one table (types, defaults,
        PK, uniqueness, max_length).

        Purpose
        -------
        ``get_schema_overview`` only returns column names + PK flag. The AI
        needs data types, nullability, defaults, uniqueness, and max length
        to write type-correct SQL (e.g. choosing CAST vs CONVERT, knowing
        which columns accept NULL, knowing the max VARCHAR length before
        truncation). This tool fills that gap without forcing the AI to run
        a separate ``SELECT * FROM information_schema.columns`` query.

        Returns
        -------
        ``{"success": True, "table": <name>, "columns": [...],
        "constraints": [...], "column_count": N}`` on success, or
        ``{"error": ...}`` on failure.
        """
        from service.database.adapters import get_adapter
        from service.database.context_sync import get_default_context_sync

        if not table_name:
            return {"error": "Table name is required"}

        context_sync = get_default_context_sync()
        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        db_type = connection.get("db_type", "postgresql")
        database = connection.get("database")
        schema = connection.get("schema", "public")

        try:
            adapter = get_adapter(db_type)
            query, params = adapter.get_table_details_query(table_name, db_name=database, schema=schema)

            if query is None:
                return {"error": f"Table details query not supported for {db_type}"}

            columns: List[Dict] = []
            constraints: List[Dict] = []
            with get_tool_connection(db_config) as conn:
                cursor = None
                try:
                    cursor = conn.cursor()
                    cursor.execute(query, params)

                    for row in cursor.fetchall():
                        col = {
                            "name": row[0],
                            "data_type": row[1],
                            "is_nullable": (str(row[2]).upper() == "YES" if row[2] is not None else True),
                            "default": row[3],
                            "is_primary_key": bool(row[4]) if row[4] is not None else False,
                            "is_unique": bool(row[5]) if row[5] is not None else False,
                            "max_length": row[6],
                        }
                        columns.append(col)
                        # Synthesize constraint entries from the PK / UNIQUE
                        # flags so the AI sees a uniform "constraints" list
                        # regardless of adapter. Detailed constraint names
                        # are intentionally omitted — they vary by DBMS and
                        # the per-column flags already convey the semantic.
                        if col["is_primary_key"]:
                            constraints.append(
                                {
                                    "type": "PRIMARY KEY",
                                    "column": col["name"],
                                }
                            )
                        if col["is_unique"] and not col["is_primary_key"]:
                            constraints.append(
                                {
                                    "type": "UNIQUE",
                                    "column": col["name"],
                                }
                            )
                finally:
                    # FIX [H5]: close the cursor even when execute/fetch raises.
                    if cursor is not None:
                        try:
                            cursor.close()
                        except Exception:
                            pass

            return {
                "success": True,
                "table": table_name,
                "columns": columns,
                "constraints": constraints,
                "column_count": len(columns),
            }
        except Exception as e:
            logger.exception("Error getting table details for %s", table_name)
            return {"error": str(e)}

    @staticmethod
    def _get_table_row_count(user_id: str, db_config: dict, table_name: str) -> Dict:
        """Get the row count for a table.

        Purpose
        -------
        ``DatabaseOperations.get_table_row_count`` already exists in
        ``operations.py`` but is only exposed via the UI. The AI currently
        has to run ``SELECT COUNT(*) FROM <table>`` via execute_query,
        which is slower (goes through the full SQL security parser, sets
        statement timeouts, etc.) and consumes the per-conversation row
        budget. This tool exposes the existing fast path directly.

        Returns
        -------
        ``{"success": True, "table": <name>, "row_count": N,
        "is_estimate": False}`` on success, or ``{"error": ...}`` on
        failure. The count is exact (not a pg_class estimate) because the
        underlying operation runs ``SELECT COUNT(*)``.
        """
        from service.database.context_sync import get_default_context_sync
        from service.database.operations import DatabaseOperations

        if not table_name:
            return {"error": "Table name is required"}

        context_sync = get_default_context_sync()
        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        database = connection.get("database")

        try:
            count = DatabaseOperations.get_table_row_count(db_config, table_name, database)
            return {
                "success": True,
                "table": table_name,
                "row_count": int(count),
                # The underlying operation runs SELECT COUNT(*), so the
                # count is exact (not a pg_class / sys.partitions estimate).
                "is_estimate": False,
            }
        except Exception as e:
            logger.exception("Error getting row count for table %s", table_name)
            return {"error": str(e)}

    @staticmethod
    def _list_views(user_id: str, db_config: dict) -> Dict:
        """List all views (and materialized views where supported) in the
        connected database / schema.

        Purpose
        -------
        ``get_schema_overview`` and ``get_tables_query`` filter
        ``table_type = 'BASE TABLE'`` only, leaving views invisible to the
        AI. This tool lets the AI discover view definitions so it can
        reason about derived tables and avoid generating redundant queries
        that duplicate an existing view's logic.

        Returns
        -------
        ``{"success": True, "views": [...], "materialized_views": [...],
        "count": N}`` on success, or ``{"error": ...}`` on failure.
        """
        from service.database.adapters import get_adapter
        from service.database.context_sync import get_default_context_sync

        context_sync = get_default_context_sync()
        connection = context_sync.get_connection(user_id)
        if not connection.get("connected"):
            return {"error": "Not connected to any database"}

        db_type = connection.get("db_type", "postgresql")
        database = connection.get("database")
        schema = connection.get("schema", "public")

        try:
            adapter = get_adapter(db_type)

            views: List[str] = []
            materialized_views: List[str] = []

            with get_tool_connection(db_config) as conn:
                cursor = None
                try:
                    cursor = conn.cursor()

                    # Regular views.
                    v_query, v_params = adapter.get_views(schema=schema, db_name=database)
                    if v_query:
                        cursor.execute(v_query, v_params) if v_params else cursor.execute(v_query)
                        views = [row[0] for row in cursor.fetchall()]

                    # Materialized views (only PostgreSQL and Oracle
                    # support them; the base adapter returns None).
                    mv = adapter.get_materialized_views(schema=schema, db_name=database)
                    if mv:
                        mv_query, mv_params = mv
                        if mv_query:
                            cursor.execute(mv_query, mv_params) if mv_params else cursor.execute(mv_query)
                            materialized_views = [row[0] for row in cursor.fetchall()]
                finally:
                    # FIX [H5]: close the cursor even when execute/fetch raises.
                    if cursor is not None:
                        try:
                            cursor.close()
                        except Exception:
                            pass

            return {
                "success": True,
                "views": views,
                "materialized_views": materialized_views,
                "count": len(views) + len(materialized_views),
            }
        except Exception as e:
            logger.exception("Error listing views")
            return {"error": str(e)}
